/* Auto-generated by Tools/scripts/generate_opcode_h.py from Lib/opcode.py */
#ifndef Py_OPCODE_H
#define Py_OPCODE_H
#ifdef __cplusplus
extern "C" {
#endif


/* Instruction opcodes for compiled code */
#define GET_AITER                         2
#define BEFORE_WITH                       3
#define YIELD_VALUE                       5
#define ASYNC_GEN_WRAP                    6
#define LOAD_ASSERTION_ERROR             10
#define LIST_TO_TUPLE                    11
#define GET_AWAITABLE                    14
#define UNARY_NEGATIVE                   20
#define POP_TOP                          23
#define WITH_EXCEPT_START                24
#define GET_LEN                          25
#define LOAD_BUILD_CLASS                 26
#define PREP_RERAISE_STAR                30
#define GET_ANEXT                        33
#define SETUP_ANNOTATIONS                37
#define NOP                              38
#define UNARY_POSITIVE                   43
#define POP_EXCEPT                       44
#define HAVE_ARGUMENT                    90
#define GET_YIELD_FROM_ITER              47
#define RETURN_VALUE                     48
#define IMPORT_STAR                      49
#define MATCH_MAPPING                    50
#define PRINT_EXPR                       52
#define RETURN_GENERATOR                 54
#define DELETE_SUBSCR                    55
#define UNARY_INVERT                     56
#define STORE_SUBSCR                     58
#define GET_ITER                         62
#define BEFORE_ASYNC_WITH                64
#define UNARY_NOT                        69
#define END_ASYNC_FOR                    70
#define MATCH_SEQUENCE                   73
#define BINARY_SUBSCR                    74
#define PUSH_EXC_INFO                    76
#define MATCH_KEYS                       77
#define BUILD_SLICE                      90
#define RAISE_VARARGS                    91
#define BUILD_MAP                        92
#define LOAD_FAST                        93
#define DELETE_ATTR                      94
#define BUILD_SET                        95
#define IS_OP                            96
#define LOAD_CONST                       99
#define LOAD_DEREF                      100
#define SEND                            102
#define JUMP_IF_NOT_EXC_MATCH           103
#define JUMP_IF_NOT_EG_MATCH            104
#define DELETE_FAST                     105
#define BUILD_LIST                      106
#define STORE_ATTR                      107
#define MAKE_CELL                       108
#define BINARY_OP                       109
#define CONTAINS_OP                     110
#define JUMP_ABSOLUTE                   111
#define POP_JUMP_IF_NONE                112
#define DELETE_DEREF                    113
#define BUILD_TUPLE                     114
#define UNPACK_EX                       115
#define SWAP                            116
#define FOR_ITER                        117
#define JUMP_FORWARD                    118
#define JUMP_NO_INTERRUPT               119
#define LOAD_CLOSURE                    120
#define STORE_GLOBAL                    121
#define POP_JUMP_IF_FALSE               122
#define DELETE_NAME                     123
#define POP_JUMP_IF_NOT_NONE            124
#define STORE_FAST                      125
#define STORE_NAME                      127
#define JUMP_IF_FALSE_OR_POP            128
#define IMPORT_FROM                     129
#define STORE_DEREF                     130
#define LOAD_ATTR                       131
#define COMPARE_OP                      132
#define UNPACK_SEQUENCE                 133
#define JUMP_IF_TRUE_OR_POP             134
#define LOAD_NAME                       135
#define DELETE_GLOBAL                   136
#define POP_JUMP_IF_TRUE                137
#define IMPORT_NAME                     138
#define RERAISE                         139
#define MAKE_FUNCTION                   140
#define LOAD_GLOBAL                     141
#define COPY                            142
#define CALL_FUNCTION_EX                143
#define EXTENDED_ARG                    144
#define SET_UPDATE                      146
#define LOAD_CLASSDEREF                 147
#define DICT_UPDATE                     148
#define BUILD_STRING                    150
#define SET_ADD                         151
#define MATCH_CLASS                     153
#define MAP_ADD                         154
#define KW_NAMES                        155
#define DICT_MERGE                      156
#define COPY_FREE_VARS                  158
#define LIST_APPEND                     159
#define BUILD_CONST_KEY_MAP             168
#define PRECALL_FUNCTION                169
#define LOAD_METHOD                     170
#define FORMAT_VALUE                    172
#define PRECALL_METHOD                  175
#define RESUME                          176
#define LIST_EXTEND                     177
#define CALL                            179
#define BINARY_OP_ADAPTIVE                1
#define BINARY_OP_ADD_INT                 4
#define BINARY_OP_ADD_FLOAT               7
#define BINARY_OP_ADD_UNICODE             8
#define BINARY_OP_INPLACE_ADD_UNICODE     9
#define BINARY_OP_MULTIPLY_INT           12
#define BINARY_OP_MULTIPLY_FLOAT         13
#define BINARY_OP_SUBTRACT_INT           15
#define BINARY_OP_SUBTRACT_FLOAT         16
#define COMPARE_OP_ADAPTIVE              17
#define COMPARE_OP_FLOAT_JUMP            18
#define COMPARE_OP_INT_JUMP              19
#define COMPARE_OP_STR_JUMP              21
#define BINARY_SUBSCR_ADAPTIVE           22
#define BINARY_SUBSCR_GETITEM            27
#define BINARY_SUBSCR_LIST_INT           28
#define BINARY_SUBSCR_TUPLE_INT          29
#define BINARY_SUBSCR_DICT               31
#define STORE_SUBSCR_ADAPTIVE            32
#define STORE_SUBSCR_LIST_INT            34
#define STORE_SUBSCR_DICT                35
#define CALL_ADAPTIVE                    36
#define CALL_BUILTIN_CLASS               39
#define CALL_NO_KW_BUILTIN_O             40
#define CALL_NO_KW_BUILTIN_FAST          41
#define CALL_BUILTIN_FAST_WITH_KEYWORDS  42
#define CALL_NO_KW_LEN                   45
#define CALL_NO_KW_ISINSTANCE            46
#define CALL_PY_EXACT_ARGS               51
#define CALL_PY_WITH_DEFAULTS            53
#define CALL_NO_KW_LIST_APPEND           57
#define CALL_NO_KW_METHOD_DESCRIPTOR_O   59
#define CALL_NO_KW_METHOD_DESCRIPTOR_NOARGS  60
#define CALL_NO_KW_STR_1                 61
#define CALL_NO_KW_TUPLE_1               63
#define CALL_NO_KW_TYPE_1                65
#define CALL_NO_KW_METHOD_DESCRIPTOR_FAST  66
#define JUMP_ABSOLUTE_QUICK              67
#define LOAD_ATTR_ADAPTIVE               68
#define LOAD_ATTR_INSTANCE_VALUE         71
#define LOAD_ATTR_WITH_HINT              72
#define LOAD_ATTR_SLOT                   75
#define LOAD_ATTR_MODULE                 78
#define LOAD_GLOBAL_ADAPTIVE             79
#define LOAD_GLOBAL_MODULE               80
#define LOAD_GLOBAL_BUILTIN              81
#define LOAD_METHOD_ADAPTIVE             82
#define LOAD_METHOD_CACHED               83
#define LOAD_METHOD_CLASS                84
#define LOAD_METHOD_MODULE               85
#define LOAD_METHOD_NO_DICT              86
#define RESUME_QUICK                     87
#define STORE_ATTR_ADAPTIVE              88
#define STORE_ATTR_INSTANCE_VALUE        89
#define STORE_ATTR_SLOT                  97
#define STORE_ATTR_WITH_HINT             98
#define LOAD_FAST__LOAD_FAST            101
#define STORE_FAST__LOAD_FAST           126
#define LOAD_FAST__LOAD_CONST           145
#define LOAD_CONST__LOAD_FAST           149
#define STORE_FAST__STORE_FAST          152
#define DO_TRACING                      255
#ifdef NEED_OPCODE_JUMP_TABLES
static uint32_t _PyOpcode_RelativeJump[8] = {
    0U,
    0U,
    0U,
    6291520U,
    0U,
    0U,
    0U,
    0U,
};
static uint32_t _PyOpcode_Jump[8] = {
    0U,
    0U,
    0U,
    350323136U,
    577U,
    0U,
    0U,
    0U,
};
#endif /* OPCODE_TABLES */

#define HAS_CONST(op) (false\
    || ((op) == 99) \
    || ((op) == 155) \
    )

#define NB_ADD                            0
#define NB_AND                            1
#define NB_FLOOR_DIVIDE                   2
#define NB_LSHIFT                         3
#define NB_MATRIX_MULTIPLY                4
#define NB_MULTIPLY                       5
#define NB_REMAINDER                      6
#define NB_OR                             7
#define NB_POWER                          8
#define NB_RSHIFT                         9
#define NB_SUBTRACT                      10
#define NB_TRUE_DIVIDE                   11
#define NB_XOR                           12
#define NB_INPLACE_ADD                   13
#define NB_INPLACE_AND                   14
#define NB_INPLACE_FLOOR_DIVIDE          15
#define NB_INPLACE_LSHIFT                16
#define NB_INPLACE_MATRIX_MULTIPLY       17
#define NB_INPLACE_MULTIPLY              18
#define NB_INPLACE_REMAINDER             19
#define NB_INPLACE_OR                    20
#define NB_INPLACE_POWER                 21
#define NB_INPLACE_RSHIFT                22
#define NB_INPLACE_SUBTRACT              23
#define NB_INPLACE_TRUE_DIVIDE           24
#define NB_INPLACE_XOR                   25

#define HAS_ARG(op) ((op) >= HAVE_ARGUMENT)

/* Reserve some bytecodes for internal use in the compiler.
 * The value of 240 is arbitrary. */
#define IS_ARTIFICIAL(op) ((op) > 240)

#ifdef __cplusplus
}
#endif
#endif /* !Py_OPCODE_H */
